### PR TITLE
Add category deletion and global category creation improvements

### PR DESCRIPTION
**Pull request by oplik0**
Resolves the second part of #4 

Adds a privilege for deleting a category (separate from modmin privilege just like assigning groups) - if a user is granted this privilege (or is an admin) he will see a deletion button in modmin interface for all categories has this privilege on. 
On a button press, a confirmation prompt will appear to ensure it wasn't accidental.
By default this button will disable the category and remove "manage category" privilege for that person.
However, this behavior can be changed in acp to actually delete the category (that is, purge it; it's an irreversible action).

Additionally, I added defaultLang in plugin.json - if there is no translation for user language, NodeBB will use en_US translation as a fallback.

(and btw. this is probably first of a few features I'll add before this year ends :) I'll try to add uploading a category image and some better category creation options - so that you can have some kind of category approval system if you want to let any users create one, but with some oversight)

### CODE REVIEW

**Comment by oplik0** [comment]
Some new things that I add here to not spam with PR's that build on top on each other:

Made the plugin more suited to forums where users can create categories themselves (#2).
Improves on the front end by having a "create category" instead of "create subcategory" (I added Polish and English versions, but I don't feel comfortable enough in German to add this translation :V).

Added also some options:
1. Option to disable global categories created by normal users (administrators and global moderators don't are unaffected) and notify an administrator about a new category (basically, a simple category creation verification system)
2. Option to force group (and badge) creation for users that don't have Assign Groups global privilege (so you can just give global modmin privilege and users can't create global categories without an associated group)
3. Option to decide if you want to change default privileges with group creation (normally if a group is created registered users, guests and spiders lose their default privileges, but you can prevent that for global categories)
4. Option to disable assigning a different category/group owner if user doesn't have Assign Group global privilege

And additionally you can create a link that will open a global category creation modal automatically by adding `#addCategory` to a global modmin link (so `/modmin#addCategory` or `/modmin/category#addCategory`, but not `/modmin/16#addCategory`) that can be used to add category creation to navigation, for example.

To activate it all, you just need to give someone global modmin privilege. If you just give out category-specific privileges - this change doesn't change anything.

(So next up on my list are category images :)

**Comment by yariplus** [comment]
Hey! This all looks great. I will review and merge in today.

**Comment by yariplus** [comment]
I couldn't get this to work on 1.13.x, async functions aren't working, since they use the new format. Need to have them updated before I can publish.

**Comment by oplik0** [comment]
interesting, since I wrote it and tested only on 1.13.x :D I expected it to be incompatible with 1.12, but the plug-in is now anyway (a fix for 1.13 made it incomp with 1.12) But I'll have to test it more - perhaps I broke something after I tested it, or something.

**Comment by oplik0** [comment]
> 
> 
> I couldn't get this to work on 1.13.x, async functions aren't working, since they use the new format. Need to have them updated before I can publish.

Nope, I have no idea what's wrong. Tested it on a mostly clear `NodeBB/master` installation and totally fresh `1.13.x` install - both work.
One bug I found was that for some reason notifications showed `Guest` instead of category name, but I fixed that and will make a PR for that soon.
Another bug I haven't fixed yet is that you can't edit disabled categories, but it was there earlier I think (`/api/category/:cid` doesn't return anything when a category is disabled, so the method for generating the modal never gets the category data)

Could you describe what doesn't work or what errors are you getting?

**Comment by yariplus** [comment]
ahh, might be because I tested on a non-fresh install. Stay tuned.

**Comment by oplik0** [comment]
Even then, some info about the error might be useful. If some other plugin or unusual data broke it, then it still might need fixing.

**Pull request merged**
